import { defineConfig, type Plugin } from "vite";

const stableBundlePlugin = (): Plugin => ({
  name: "stable-bundle",
  generateBundle(_, bundle) {
    const entryChunk = Object.values(bundle).find(
      (output): output is import("rollup").OutputChunk =>
        output.type === "chunk" && output.isEntry,
    );

    if (!entryChunk) {
      this.error("Unable to locate the entry chunk for the Tea Timer Card build.");
      return;
    }

    const lines = [
      "// Stable entry point for Home Assistant (generated by Vite).",
      `export * from "./${entryChunk.fileName}";`,
      `import "./${entryChunk.fileName}";`,
      "",
    ];

    this.emitFile({
      type: "asset",
      fileName: "tea-timer-card.js",
      source: lines.join("\n"),
    });
  },
});

export default defineConfig({
  build: {
    lib: {
      entry: "src/index.ts",
      name: "TeaTimerCard",
      formats: ["es"],
    },
    rollupOptions: {
      output: {
        entryFileNames: "tea-timer-card.[hash].js",
        inlineDynamicImports: true,
      },
      plugins: [stableBundlePlugin()],
    },
    sourcemap: true,
    target: "es2019",
    emptyOutDir: true,
  },
  test: {
    environment: "jsdom",
    setupFiles: "./vitest.setup.ts",
    coverage: {
      provider: "istanbul",
      include: ["src/time/**/*.ts"],
      thresholds: {
        perFile: true,
        statements: 95,
        branches: 95,
        functions: 95,
        lines: 95,
      },
    },
  },
});
