name: Docs checks

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'docs/**'
      - 'README.md'
      - 'examples/**'
      - '.github/workflows/docs.yml'
      - 'package.json'
      - 'package-lock.json'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run documentation checks
        run: npm run docs:check
