name: Playwright E2E

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build demo assets
        run: npm run build

      - name: Run Playwright tests
        run: PLAYWRIGHT_SKIP_BUILD=1 npm run e2e:ci
