name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Build, verify, and publish artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type-check
        run: npm run typecheck

      - name: Run unit tests
        run: npm test

      - name: Build distributable
        run: npm run build

      - name: Verify release artifacts
        run: npm run release:verify

      - name: Generate SHA-256 checksums
        run: npm run release:checksums

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tea-timer-card-dist
          if-no-files-found: error
          path: |
            dist/**
            checksums.txt

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/tea-timer-card.js
            dist/tea-timer-card.*.js
            dist/tea-timer-card.*.js.map
            checksums.txt
          body_path: docs/releases/${{ github.ref_name }}.md
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
